// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/d096530e29e7d996df86f55e81522824f16bc02a/express-myconnection/index.d.ts
declare namespace mysql{
  export interface IConnection {}
  export interface IError {}
}

declare namespace Express {

  export interface Request {
    getConnection?: (callback: (err: mysql.IError, connection: mysql.IConnection) => void) => void;
  }
}

declare module "express-myconnection" {
  import express = require('express');
  import mysql = require('mysql');

  function connection(mysql: mysql.IMySql, dbConfig: mysql.IConnectionConfig, strategy: string): express.RequestHandler;

  export = connection;
}
